export { Hero } from './Hero'
export { Features } from './Features'
export { HowItWorks } from './HowItWorks'
export { Comparison } from './Comparison'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
